name: Selenium Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '10 20 * * *'  # Her gün saat 20:10'da UTC çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t selenium-tests .

    - name: Run Docker container
      run: |
        docker run -d --name selenium-tests selenium-tests
        docker cp selenium-tests:/app/data /github/workspace/data

    - name: Upload JSON files
      uses: actions/upload-artifact@v3
      with:
        name: json-files
        path: /github/workspace/data

    - name: Clean up
      run: docker rm -f selenium-tests
